### ISSUE TITLE
Gnome platform 42 is End of Life, please update

### ISSUE THREAD

**Issue by Scotty-Trees** [GustavoPeredo/Font-Downloader#105]
Greetings,

During a `flatpak update` command today I was notified of the following:

> "Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason: The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform. Info: applications using this runtime: org.gustavoperedo.FontDownloader"

I just wanted to bring this to attention and hope it can be resolved in the near future. Would very much like to see your application updated to maintain proper support, thank you.

**Comment by GustavoPeredo** [comment]
Thanks for the notice, it should be updated now. Happy easter!
