### ISSUE TITLE
Filter Fonts by Language

### ISSUE THREAD

**Issue by Ibragimov** [GustavoPeredo/font-downloader#11]
Dear Gustavo,

In addition to filter by "Font Type", could you please, add a feature to filter by "Language" to easily search for Tajik and Russian or Cyrillic based compatible fonts:

Example of Compatible font for Cyrillic based languages:
![Compatible](https://user-images.githubusercontent.com/1321588/94807616-53ad1180-0409-11eb-8d00-7794dd630965.jpg)

Example of Incompatible font for Cyrillic based languages:
![Incompatible](https://user-images.githubusercontent.com/1321588/94807620-56a80200-0409-11eb-935c-142b2b6dc707.jpg)

Thank you for prompt reply,
Victor Ibragimov

**Comment by GustavoPeredo** [comment]
Yes! I'm already working on it. You can see what I'm working on by checking the very bottom of my README file:

* Add new filters (depending on alphabet, will probably require a redesign of the app)

**Comment by Ibragimov** [comment]
Please, let me know once ready, so I can help you with translations on new features.

Have a great day!
Victor Ibragimov

**Comment by GustavoPeredo** [comment]
Feature was added, together with lots of others!

Good day for you too ;)

**Comment by Ibragimov** [comment]
Tajik and Russian translations for new features is now 100% completed!

[Font_Downloader_Tajik.zip](https://github.com/GustavoPeredo/font-downloader/files/5316480/Font_Downloader_Tajik.zip)
[Font_Downloader_Russian.zip](https://github.com/GustavoPeredo/font-downloader/files/5316482/Font_Downloader_Russian.zip)

**Comment by Ibragimov** [comment]
Both files are exported from POEditor

**Comment by GustavoPeredo** [comment]
Thank you very much for your work ;)
