### ISSUE TITLE
Wide availability on standard repositories

### ISSUE THREAD

**Issue by Ibragimov** [GustavoPeredo/font-downloader#12]
Dear Gustavo,

Could you please, make Font Downloader widely available on standard repositories for easier installation and upgrade on any distributions, like Debian, Ubuntu, KDE neon, Linux Mint, Mageia and others on command line as sudo apt install fontdownloader or via Software managers?

Thank you for prompt reply,
Victor Ibragimov

**Comment by GustavoPeredo** [comment]
While I have no problems on having my app published on other repositories and I think it would be very useful for users on KDE Plasma to have their color scheme applied to the app, midterms will happen next week and I won't have as much time to code/research.

Also, I don't know any resource to help me publish the app on official repositories, I could technically create a ppa and a copr, but I feel like this will be too much effort for little change.

If you are a maintainer or know someone that is a maintainer of packages in official repositories, I'll gladly enter in contact to ask  how to submit my application, but for now Flatpak is the only way I'll distribute the binary.

**Comment by Ibragimov** [comment]
Do you plan to have a version of Font Downloader for Windows as well?

**Comment by GustavoPeredo** [comment]
No, I don't plan to port Font Downloader to Windows for now. Mostly because of the lack of documentation, specially regarding GTK2Webkit.

Maybe in the future...
