### ISSUE TITLE
Not starting in Ubuntu 20.1

### ISSUE THREAD

**Issue by miguelperedo** [GustavoPeredo/font-downloader#16]
Hi,
I installed it on a fresh installation of Ubuntu. when running I got the following message:

flatpak run org.gustavoperedo.FontDownloader
Gtk-Message: 12:09:20.512: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/app/share/fontdownloader/fontdownloader/main.py", line 38, in do_activate
    win = FontdownloaderWindow(application=self)
  File "/app/share/fontdownloader/fontdownloader/window.py", line 215, in __init__
    self.checkForInstalledFonts()
  File "/app/share/fontdownloader/fontdownloader/window.py", line 444, in checkForInstalledFonts
    onlyfiles = [f for f in listdir(defaultPath) if path.isfile(path.join(defaultPath, f))]
FileNotFoundError: [Errno 2] No such file or directory: '/home/parallels/.local/share/fonts'
Gtk-Message: 12:09:21.217: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:09:21.218: Failed to load module "canberra-gtk-module"

**Comment by GustavoPeredo** [comment]
Hmmm, that's interesting. I'll fix this right now. 
In the time being, simply running: `mkdir /home/parallels/.local/share/fonts` should fix your issue.
Thanks for the report.

**Comment by GustavoPeredo** [comment]
Okay, the fix is done! Next version will not have this issue, thank you very much.
