### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/app/share/fontdownloader/fontdownloader/webfonts.json'

### ISSUE THREAD

**Issue by rffontenelle** [GustavoPeredo/font-downloader#18]
The following exception is raised when launching font-downloader:
```
$ fontdownloader 
Traceback (most recent call last):
  File "/usr/bin/fontdownloader", line 40, in <module>
    from fontdownloader import main
  File "/usr/share/fontdownloader/fontdownloader/main.py", line 27, in <module>
    from .window import FontdownloaderWindow
  File "/usr/share/fontdownloader/fontdownloader/window.py", line 30, in <module>
    webfontsData = json.load(open("/app/share/fontdownloader/fontdownloader/webfonts.json", 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/app/share/fontdownloader/fontdownloader/webfonts.json'
```

Environment: Arch Linux 64-bit, font-downloader built from latest commit (0016e0a3)

**Comment by GustavoPeredo** [comment]
Just to make sure, you compilar from source, right?

**Comment by GustavoPeredo** [comment]
Hopefully this issue only happened when compiling from source on your machine, I was able to debug the problem, the code should be up to date now.

**Comment by rffontenelle** [comment]
Yes, I built locally on my system using meson commands. Sorry for not being clear about it.

**Comment by GustavoPeredo** [comment]
Can you try the new version? Should be working now

**Comment by GustavoPeredo** [comment]
I will close the issue, but If the error persist feel free to comment

**Comment by rffontenelle** [comment]
Sorry for the delay. I tested it right now and it works. Thanks!

**Comment by GustavoPeredo** [comment]
No problem, thank you for the report
