### ISSUE TITLE
Incorrect application name in pt-br

### ISSUE THREAD

**Issue by fealv** [GustavoPeredo/font-downloader#22]
"Intalador" is wrong, the correct is "Instalador"
![image](https://user-images.githubusercontent.com/60493079/97117501-f132f280-16e2-11eb-9b9c-0c819cb5d6b8.png)

**Comment by GustavoPeredo** [comment]
Thank you! I forgot to push to Flathub the fix for that. It takes around 1 day for updates to reach Flathub users.

**Comment by GustavoPeredo** [comment]
Fixed

**Comment by fealv** [comment]
Thank you!
