### ISSUE TITLE
Add Support for select Styles

### ISSUE THREAD

**Issue by litch0** [GustavoPeredo/Font-Downloader#27]
Bassically, I would like to know if it is possible to add support for this:
![image](https://user-images.githubusercontent.com/57605930/100238995-9eca3900-2f0f-11eb-8b94-b2cb17676db5.png)

**Comment by GustavoPeredo** [comment]
I have an idea on how to implement this, updates will come soon

**Comment by litch0** [comment]
Cool

**Comment by litch0** [comment]
## Helpfull information:
Talking the change between this 2 urls:
https://fonts.googleapis.com/css2?family=Hanalei+Fill&display=swap
https://fonts.googleapis.com/css2?family=Hanalei+Fill

I didn't notice diference in the request, but i think since google puts it there by default, i think it is important to have, but the response is the same
https://fonts.googleapis.com/css2?family=Hanalei+Fill
https://fonts.googleapis.com/css2?family=Hanalei+Fill&family=Roboto:ital,wght@0,100;1,100

I think i notice a patern in the url
```Python
base = "https://fonts.googleapis.com/css2?"
```

**Comment by litch0** [comment]
## Helpfull information:
Talking the change between this 2 urls:
https://fonts.googleapis.com/css2?family=Hanalei+Fill&display=swap
https://fonts.googleapis.com/css2?family=Hanalei+Fill

I didn't notice diference in the request, but i think since google puts it there by default, i think it is important to have, but the response is the same
https://fonts.googleapis.com/css2?family=Hanalei+Fill
https://fonts.googleapis.com/css2?family=Hanalei+Fill&family=Roboto:ital,wght@0,100;1,100

I think i notice a patern in the url
`https://fonts.googleapis.com/css2` this seems to be the base of all of the css fonts
then for every new family you want to add, it follows as, warning, this will get complicated
for single style just use
`family=<name>:<style1>@<number i dont understand for style1>`
for more styles you just add `,` and  or `;` depending where your are at, example:
`family=<name>:<style1>,<style2>@<number i dont understand for style1>;<number i dont understand for style1>`
let's call this `n`.
for more styles at once, the work is to put a `&` before the next `n` so it would be `base?n[&n&n&n&n...]`
the numer i dont understand is this

![Screenshot from 2020-12-30 21-03-44](https://user-images.githubusercontent.com/57605930/103387508-f77a8c00-4ae2-11eb-9479-01aa2a9ea3fe.png)

**Comment by litch0** [comment]
Example:
1 font:
![Screenshot from 2020-12-30 21-14-30](https://user-images.githubusercontent.com/57605930/103387722-162d5280-4ae4-11eb-8c55-fd128bc269e4.png)
![Screenshot from 2020-12-30 21-14-46](https://user-images.githubusercontent.com/57605930/103387723-16c5e900-4ae4-11eb-86c4-53be99c48b81.png)

More than 1:
![Screenshot from 2020-12-30 21-15-59](https://user-images.githubusercontent.com/57605930/103387766-512f8600-4ae4-11eb-8cc9-d5c483d4d077.png)
![Screenshot from 2020-12-30 21-16-10](https://user-images.githubusercontent.com/57605930/103387767-51c81c80-4ae4-11eb-9499-e9159538bf99.png)

**Comment by litch0** [comment]
I hope it help

**Comment by GustavoPeredo** [comment]
It's been pushed to master, to use the feature go to:
Settings > Developer Window > Select any font
:)
