### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by manuq** [GustavoPeredo/Font-Downloader#28]
Hi,
I updated the Spanish translation in poeditor.com. Mainly to match GNOME Fonts by translating "font" to "tipografía", which is more appropiate than the current "fuente". Could you trigger a new release?

**Comment by GustavoPeredo** [comment]
Thank you very much for your contribution, I plan on updating the app soon.

**Comment by GustavoPeredo** [comment]
The update should get to you tomorrow!

**Comment by manuq** [comment]
> The update should get to you tomorrow!

Thank you! I just updated the flatpak and I see the translation! Another thing that could be nice to translate is the pangram sample text "The quick brown fox...". It is translated in GNOME Fonts with this Spanish pangram:

> Jovencillo emponzoñado de whisky, ¡qué figurota exhibes!

**Comment by manuq** [comment]
I just submitted a MR for translating the pandoc: https://gitlab.gnome.org/GustavoPeredo/font-downloader/-/merge_requests/3
