### ISSUE TITLE
Font source and version indication

### ISSUE THREAD

**Issue by JeffRockatansky** [GustavoPeredo/Font-Downloader#29]
Some fonts are updating regularly. E.g. [FiraCode](https://github.com/tonsky/FiraCode) has [version 5.2](https://github.com/tonsky/FiraCode/releases/tag/5.2) released June 12.

It will be much more informative and convenient if there was an indication of from where and which version of the font I'm downloading with this tool.

**Comment by GustavoPeredo** [comment]
Yes! That's an awesome idea! Every month I update the fonts' sources, but it would be nice to show that information as well.

**Comment by GustavoPeredo** [comment]
Hello! Good news for you! I implemented this functionality!
To search for installed fonts or fonts with updates, simply search for "update" or "installed" on the search bar, there is also a little tag saying that the font has updates available.

The update is on master
