### ISSUE TITLE
Tajik Language Support

### ISSUE THREAD

**Issue by Ibragimov** [GustavoPeredo/font-downloader#3]
Hi,

Could you please, add Tajik language for Font Downloader.

Thank you for prompt reply,
Victor Ibragimov

**Comment by GustavoPeredo** [comment]
Hello! I'd really like to do so, but first I need to figure translations in general out. I'm trying, hopefully this week I can already implement the functionality.

Once the functionality is implemented, would you like to help with the Tajik translations?

**Comment by Ibragimov** [comment]
Hi,

Yes, I will help with Tajik translations. Please, let me know once functionality for it is ready.

Kind regards,
Victor Ibragimov

**Comment by GustavoPeredo** [comment]
It is done! Language support has been implemented. Use this link if you want to help translations with POEditor: https://poeditor.com/join/project?hash=hfnXv8Iw4o.

I'll close this issue once translations are ready for release. Thank you!

**Comment by Ibragimov** [comment]
Tajik and Russian languages are now 100% translated!

**Comment by Ibragimov** [comment]
[Font_Downloader_Tajik_Russian.zip](https://github.com/GustavoPeredo/font-downloader/files/5303759/Font_Downloader_Tajik_Russian.zip)

**Comment by GustavoPeredo** [comment]
Awesome! I wil merge them today, then

**Comment by Ibragimov** [comment]
Dear Gustavo,

I have tested translations for Font Downloader. Tajik looks good! Russian is not yet available.
However, please, update both translated files with improvements for Tajik and Russian languages:
[Font_Downloader_Russian.zip](https://github.com/GustavoPeredo/font-downloader/files/5311109/Font_Downloader_Russian.zip)
[Font_Downloader_Tajik.zip](https://github.com/GustavoPeredo/font-downloader/files/5311110/Font_Downloader_Tajik.zip)

I see there are some untranslated text in the app. Could you please, make those strings translatable (underlined in red)
![Font_Downloader_Tajik_Language](https://user-images.githubusercontent.com/1321588/94796148-cca36d80-03f7-11eb-841f-650c60aaf4f5.jpg)

Have a great day!
Victor

**Comment by GustavoPeredo** [comment]
Yes, I'll add these to the translations

**Comment by Ibragimov** [comment]
Some references:
Russian Language Support: https://github.com/GustavoPeredo/font-downloader/issues/4#issue-711706867
How to compile on Ubuntu and Debian: https://github.com/GustavoPeredo/font-downloader/issues/5#issue-711873877
Filter Fonts by Language: https://github.com/GustavoPeredo/font-downloader/issues/11#issue-712785007

**Comment by Ibragimov** [comment]
Tajik translations for new features is now 100% completed!

[Font_Downloader_Tajik.zip](https://github.com/GustavoPeredo/font-downloader/files/5316480/Font_Downloader_Tajik.zip)

**Comment by Ibragimov** [comment]
More screenshots of Tajik translations. It looks like "Default" button in Settings needs to be translated. Could you please, make it translatable:
![Tajik_Language_One](https://user-images.githubusercontent.com/1321588/94990705-884ed380-0597-11eb-82c9-9319340f3afa.png)
![Tajik_Language_Three](https://user-images.githubusercontent.com/1321588/94990706-8a189700-0597-11eb-8f94-0311dea65391.png)
![Tajik_Language_Two](https://user-images.githubusercontent.com/1321588/94990707-8be25a80-0597-11eb-809c-27f3d7ecb3ff.png)

**Comment by GustavoPeredo** [comment]
Yes, I'll check that out.

**Comment by Ibragimov** [comment]
100% Translated! (on POEditor)

**Comment by Ibragimov** [comment]
Tajik Language looks good and complete now!

![Tajik_Language_Default](https://user-images.githubusercontent.com/1321588/95179642-59746f80-07da-11eb-8dd8-94fa8a545fe3.png)

**Comment by GustavoPeredo** [comment]
Awesome!
