### ISSUE TITLE
Detect when the user is typing and not in the textbox that alters the panel text to search for fonts

### ISSUE THREAD

**Issue by litch0** [GustavoPeredo/Font-Downloader#30]
When I am not typing something on the textbox that alters the text in the panel is annoying to have to use the mouse to change to search mode. Can you please add a shortcut for that or make the app like Gnome Settings, that wen you start typing and the cursor is not focus in nothing it automatically goes to search?

**Comment by GustavoPeredo** [comment]
I'll try to implement that

**Comment by GustavoPeredo** [comment]
Implemented and committed to master

**Comment by litch0** [comment]
Cool thanks
