### ISSUE TITLE
Christmas-themed icon is weird

### ISSUE THREAD

**Issue by bertob** [GustavoPeredo/Font-Downloader#31]
Changing the app icon with the season may seem cute in theory, but it's pretty jarring in practice. App icons suddenly having holiday decorations on them on your system is unexpected and weird. As a Circle app I don't think this is a good precedent to set for other apps, imagine what the app grid would look like if everyone did this :)

**Comment by GustavoPeredo** [comment]
I appreciate your feedback, while I personally would love to see all my icons wear christmas hats (specially GIMP), I agree that some users would prefer not to have a bunch of apps using them. I'll be asking for more feedback and opinions and when I get to a decisive answer, I'll close this issue.

I think I will open a thread on GNOME's discourse discussing the topic. What do you think?

**Comment by jimmac** [comment]
I would also favor not going with such a prominent easter egg. I mean santa hat. While it may be cute in a single occurrence if executed according to the style, I can see this visual repeating noise becoming annoying really fast.

**Comment by GustavoPeredo** [comment]
After further discussion with other members of the community and my lack of time to open a well structured discourse post I decided on the following:
Keep the icon until tomorrow (happy holidays for anyone reading this :P) and use it next Christmas only in the 'About' window.
