### ISSUE TITLE
Moar progressbars!

### ISSUE THREAD

**Issue by nekohayo** [GustavoPeredo/Font-Downloader#32]
Sometimes, especially with slower internet connections or latency, it can take a second or two to preview fonts, or many seconds to download+install, or to load more items in the list of fonts. In all of those situations, I think the app should show a progressbar (or spinner, or something) to indicate that something is going on and the UI (or operation) is not ready/done.

After clicking the "Install" button on the various "Fira" fonts, for example, the app locked up for nearly a minute on my end. While that is an extreme case I suppose, it would be nice if there was a progressbar or something.

**Comment by GustavoPeredo** [comment]
Thank you for your suggestions, I'll work on them since they seem nescessary

**Comment by nekohayo** [comment]
Thanks! You will probably have to do some work to make the UI not block on the main loop/thread while stuff is happening async in the background, ideally :)

**Comment by GustavoPeredo** [comment]
Implemented and pushed to master!
