### ISSUE TITLE
Croatian translation

### ISSUE THREAD

**Issue by milotype** [GustavoPeredo/Font-Downloader#38]
If you can, please add the Croatian translation from the POEditor platform.

**Comment by GustavoPeredo** [comment]
Yes sir! o7

Expect an update probably today

**Comment by GustavoPeredo** [comment]
The translation should have been updated and your name should have been added to the contributers list now! I'll be updating the app.

**Comment by GustavoPeredo** [comment]
If you want to test the Croatian translation you can do it now by using this command:
`flatpak install https://dl.flathub.org/build-repo/40841/org.gustavoperedo.FontDownloader.flatpakref`
Or you can wait until tomorrow for the build to be published.

**Comment by milotype** [comment]
Thank you! I've updated the Croatian translation at POEditor just now, with the new strings …

**Comment by GustavoPeredo** [comment]
They should've been pplied by now
