### ISSUE TITLE
Option to disable animations

### ISSUE THREAD

**Issue by litch0** [GustavoPeredo/Font-Downloader#41]
I find it really annoying the animations when opening a new font. It would be really cool if we had an option to disable it or change it.

**Comment by GustavoPeredo** [comment]
I changed animations to crossfade, they should go easier on the eye now. The update should be release in around 2 days. If you really want to have the option to disable animation then, feel free to reopen the issue.

Happy birthday as well!

**Comment by litch0** [comment]
thanks, glad u added the stuff, I feel more comfortable using the app now
