### ISSUE TITLE
Better appdata summary

### ISSUE THREAD

**Issue by bertob** [GustavoPeredo/Font-Downloader#50]
The current summary "A simple GTK font downloader." is not great (mentions the toolkit, restates information from the app name, period at the end).

I'd recommend something short and to the point, like "Download Google Fonts", "Install Google Fonts locally", or "Get Google Fonts on your computer".

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by GustavoPeredo** [comment]
Thanks for your comment! I agree with these changes, however I do plan on adding more font sources in the future, so I won't limit the description to Google Fonts only.

**Comment by bertob** [comment]
Fair enough, then maybe `Install fonts from online sources`?

**Comment by GustavoPeredo** [comment]
I thought I had replied to this issue, but apparently I didn't :P, my apologies... I changed it, feels a lot better now. Thanks for the feedback
