### ISSUE TITLE
Tags for versions

### ISSUE THREAD

**Issue by dusansimic** [GustavoPeredo/Font-Downloader#81]
Hi Gustavo! Thanks for an amazing app!

I'd just like to make a comment that git tags for versions will be very useful for package maintainer so they could know which commit should be used for a specific version. I see that in the appdata file version 8.0.0 has been added in [this commit][first] however in the [flatpak config][flatpak] [this commit][second] is used. This is very confusing for package maintainers and since I would like to make a package for Arch Linux, I'm not completely sure which commit should be used. A tag for each version would remove said confusion completely 😁.

[first]: https://github.com/GustavoPeredo/Font-Downloader/commit/837931a177618e0d43f1f4ba2d5e5d506f6bea35
[second]: https://github.com/GustavoPeredo/Font-Downloader/commit/c61f95fdc77fe6a6337310304ed4686cbf5203d3
[flatpak]: https://github.com/flathub/org.gustavoperedo.FontDownloader/blob/master/org.gustavoperedo.FontDownloader.json

**Comment by GustavoPeredo** [comment]
Okay I created a release! Thanks again!!
